### ISSUE TITLE
[FEAT] 캐츄 생성뷰 팝업 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#105]
## 💡 Issue
캐츄 생성뷰 팝업 구현하기

## 📝  todo
- [ ] 캐츄 생성 팝업 레이아웃 구현하기
- [ ] VC 연결
- [ ] close 버튼 구현
- [ ] pop 버튼 구현
