### ISSUE TITLE
[FEAT] EditAction 뷰 레이아웃 및 기능 구현

### ISSUE THREAD

**Issue by heerucan** [TeamCatchMe/CatchMe-If-You-iOS#110]
## 💡 Issue
EditAction 뷰 레이아웃과 기능 구현하기

## 📝  todo
- [x] AddAction 뷰에서 수정하기 버튼 부분만 변경하기
- [x] Character 뷰에서 수정버튼 선택 시 화면 전환 연결하기
- [x] Character 뷰 데이터 전달하기 - 캐릭터이미지
- [x] 캐릭터이름
- [x] 작성날짜
- [x] 작성내용
- [x] 작성이미지
- [x] 뒷 컬러
