### ISSUE TITLE
[FEAT] Character 뷰 서버 통신

### ISSUE THREAD

**Issue by heerucan** [TeamCatchMe/CatchMe-If-You-iOS#117]
## 💡 Issue
Character 뷰 서버 통신 - GET

## 📝  todo
- [x] 캐릭터 상세 정보 가져오기 - 이름, 생성날짜, 잠금
- [x] 캐릭터 이미지
- [x] content 내용, 작성일자, 업로드 이미지
- [x] 레벨, 캐치지수, 캐칭
