### ISSUE TITLE
[FEAT] 캘린더 팝업 뷰 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#12]
## 💡 Issue
캘린더에서 이벤트가 존재하는 셀을 누르면 팝업뷰가 뜨게 구현

## 📝  todo
- [x] 캘린더에서 이벤트가 있는 날만 팝업이 뜨도록 구현
- [x] 팝업뷰 전체 레이아웃 잡기
- [x] 이벤트 날짜 가져오기
- [x] 스와이프 기능 구현
- [x] 버튼 isHidden 구현
- [x] Layout -> 기종에 맞게 변경
