### ISSUE TITLE
[FEAT] 설정 뷰 서버 통신 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#126]
## 💡 Issue
설정뷰에서 서버 통신을 구현합니다.

## 📝  todo
- [ ] 비밀번호 변경 서버 통신
- [ ] 닉네임 변경 서버 통신
- [ ] 탈퇴 서버 통신
