### ISSUE TITLE
[CHORE] UX Writing 및 바뀐 부분 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#135]
## 💡 Issue
디자인, 기획 쪽에서 변경된 내용들 변경하기

## 📝  todo
- [x] 회원가입 부분 파란색 구현
- [x] 리포트 부분 님의 변경
- [x] 배경 색상 추가
- [x] 배경 색상 반영되는 부분들 뒷 배경 동그라미로 생성
