### ISSUE TITLE
[FEAT] 캐릭터 생성뷰 전체 레이아웃 구성

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#14]
## 💡 Issue
캐릭터 생성뷰 전체 레이아웃 구성하기

## 📝  todo
- [x] 전체 진행 레이아웃 잡기 
- [x] page Control 생성
- [x] 라벨 위치 잡기
- [x] 버튼 위치 잡기
