### ISSUE TITLE
[FEAT] AddAction 뷰 게시글 수정 및 삭제 서버 통신

### ISSUE THREAD

**Issue by heerucan** [TeamCatchMe/CatchMe-If-You-iOS#141]
## 💡 Issue
AddAction 뷰 게시글 수정 및 삭제 서버 통신

## 📝  todo
- [x] Edit 수정하기 버튼 -> 캐릭터 전달
- [x] 닉네임 전달
- [x] 디폴트 사진추가 깔아두기
- [ ] Edit 수정 서버 연결
- [x] Edit 삭제 서버 연결
