### ISSUE TITLE
[FEAT] Character 뷰 기능 구현

### ISSUE THREAD

**Issue by heerucan** [TeamCatchMe/CatchMe-If-You-iOS#15]
## 💡 Issue
Character 뷰에 있는 기능 구현

## 📝  todo
- [x] 캐치지수 팝업 dismiss 기능 구현
- [x] content cell 내 더보기 버튼 기능 구현
- [x] 더보기 삭제 버튼 커스텀 팝업 구현 
- [x] 기록하기 버튼 기능 구현 - 화면전환 되어야 함
