### ISSUE TITLE
[FEAT] Carousel 기능 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#16]
## 💡 Issue
캐릭터 생성뷰 Carousel 기능 구현

## 📝  todo
- [x] 옆으로 넘어가는 기능 구현
- [x] yInset 잡기
- [x] 크기 제대로 잡기
- [x] Carousel index 가져와서 캐릭터 가져오기 구현
