### ISSUE TITLE
[HOTFIX] 레이아웃 변경

### ISSUE THREAD

**Issue by heerucan** [TeamCatchMe/CatchMe-If-You-iOS#164]
## 🐞 버그 설명

자잘한 버그들과 레이아웃을 수정하려 합니다.

## 📝 todo
- [x] 데이터 피커 위치 문제 12pro 
- [x] 말풍선 양 옆 마진 레이아웃 문제
- [x] 핑크색 상단 배경 높이
- [x] 사진이 꽉 안차는 오류 수정
- [x] CharacterVC 색상 배경 전달
