### ISSUE TITLE
[HOTFIX] UI 반영 잘못된 부분 해결

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#166]
## 🐞 버그 설명
UI Color등이 잘못 들어간 부분들 수정

## 📝 todo
- [x] Color 다시 고치기
- [x] 수정 부분 연결
- [x] 유령 캐릭터 튕기는 문제 해결(문제가 있었는데 없었습니다.)
- [x] 리포트 날짜 변경되지 않는 문제 해결
- [x] 리포트에서 상세뷰 연결
