### ISSUE TITLE
[DOCS] 리드미 작성

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#17]
## 💡 Issue
리드미 작성하기

## 📝  todo
- [x] 전체 리드미 작성하기
- [x] Docs 폴더 생성하기
- [x] Coding Convention 정리
- [x] Branch 전략 정리하기
