### ISSUE TITLE
[CHORE] ReportView Layout 수정

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#30]
## 💡 Issue
ReportView가 Scroll이 되지 않기에 SE2 기종에서 나타나는 뷰 짤림 현상을 해결하기 위해서 Layout 수정

## 📝  todo
- [x] 팝업뷰 레이아웃 수정
- [x] 캘린더 레이아웃 수정
- [x] Back Button 위치 변경
