### ISSUE TITLE
[FEAT] AddCatchu뷰 플로우 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#32]
## 💡 Issue
AddCatchu뷰 안에서의 플로우를 순서대로 구현

## 📝  todo
- [x] 첫번째 뷰에서 두번째 넘어가는 플로우 구현(collectionView인덱스 받아야 함)
- [x] 두번째 뷰에서 텍스트 입력하는 부분
- [x] 두번째 뷰, 텍스트 추가되면 넘어가는 플로우 구현
- [x] 세번째 뷰, 공개 설정하는 부분 설정
- [x] 뒤로 돌아가는 플로우
