### ISSUE TITLE
[CHORE] Character 뷰 레이아웃 수정

### ISSUE THREAD

**Issue by heerucan** [TeamCatchMe/CatchMe-If-You-iOS#35]
## 💡 Issue
CharacterVC 디자인 변경에 따른 전반적인 레이아웃 수정

## 📝  todo
- [x] CharacterTVC lineView reload시 사라지는 문제 해결하기
- [x] 캐치지수 팝업 레이아웃 잡기
- [x] CharacterReportTVC 캐치지수 부분 레이아웃 고치기
- [x] pinImageView 위치 옮기기
- [x] nameLabel = byWordWraping 으로 바꿔주기
- [x] lineView 상태 표시하는 거 위치 옮기기
