### ISSUE TITLE
[CHORE] Main 뷰 empty state 레이아웃 구현

### ISSUE THREAD

**Issue by yangsubinn** [TeamCatchMe/CatchMe-If-You-iOS#39]
## 💡 Issue
MainView empty state 레이아웃 구현

## 📝  todo
- [x] 캐츄는 있는데 활동이 없는 empty state
- [x] 캐츄도 없고 활동도 없는 empty state
- [x] 슬쩍 페이지컨트롤할때 데이터 변경되는 기능도 추가..
