### ISSUE TITLE
[FEAT] AddAction 뷰 레이아웃 구현

### ISSUE THREAD

**Issue by heerucan** [TeamCatchMe/CatchMe-If-You-iOS#42]
## 💡 Issue
AddAction 뷰 전체 레이아웃 구현하기

## 📝  todo
- [x] 상단 뷰 레이아웃 잡기
- [x] 텍스트 뷰 레이아웃 잡기
- [x] se (노치 없는 기기) 레이아웃 대응해주기
- [x] 커스텀 팝업 레이아웃 잡기
