### ISSUE TITLE
[ADD] 이미지 에셋 추가

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#45]
## 💡 Issue
이미지 에셋 추가하기

## 📝  todo
- [x] 이미지 에셋 추가하기🌈🔫❤️‍🔥
- [x] 이상하게 나온 캐릭터 181번 꼭 받아서 커밋하자
- [x] 파일 빼서 편하게 캐릭터 가져갈 수 있도록 해보기
- [x] 앱아이콘 설정
