### ISSUE TITLE
[FEAT] 회원가입뷰 레이아웃 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#46]
## 💡 Issue
회원가입뷰 레이아웃을 잡습니다.

## 📝  todo
- [x] 텍스트필드 자리잡기(따로 뷰들로)
- [x] 회원가입 Top View 자리잡기
- [x] 가입하기 버튼 자리잡기
