### ISSUE TITLE
[FEAT] Character 뷰 더보기 커스텀 ActionSheet 레이아웃 및 구현

### ISSUE THREAD

**Issue by heerucan** [TeamCatchMe/CatchMe-If-You-iOS#48]
## 💡 Issue
Character 뷰 더보기 커스텀 ActionSheet 레이아웃 잡고 구현하기

## 📝  todo
- [x] 더보기 커스텀 ActionSheet 레이아웃 잡기
- [x] 더보기 커스텀 ActionSheet 기능 구현하기
- [x] 이전 더보기 커스텀 팝업 코드 삭제하기
