### ISSUE TITLE
[FEAT] Login 기능 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#54]
## 💡 Issue
Login 기능 구현하기(자동로그인 제외 -> 서버 통신 때 할 예정)
## 📝  todo
- [x] email 눌렀을 때 animate
- [x] password 눌렀을 때 animate
- [x] 밑에 텍스트 뜨는 거 구현
