### ISSUE TITLE
[FEAT] Report뷰 전체 레이아웃 구성

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#6]
## 💡 Issue
Report뷰 전체 Layout 구성

## 📝  todo
- [x] 상단 현황 Label 잡기
- [x] 캐릭터 활동 뷰 레이아웃 잡기
- [x] 캘린더 CollectionView 레이아웃 잡기
