### ISSUE TITLE
[FEAT] AddAction 뷰 TextView 기능 구현

### ISSUE THREAD

**Issue by heerucan** [TeamCatchMe/CatchMe-If-You-iOS#61]
## 💡 Issue
AddAction 뷰 TextView 기능 구현

## 📝  todo
- [x] 텍스트뷰 placeholder 추가하기
- [x] 글자수 제한하기
- [x] 선택 시에 border color 바꾸기
- [x] 키보드 dimiss 구현하기
- [x] 키보드 선택 시에 view 올리기
- [x] 텍스트뷰 패딩 추가하기 
- [x] 글자 입력 시에 letterNumLabel에도 적용시켜주기
- [x] 커서 색깔 적용하기
