### ISSUE TITLE
[FEAT] 리포트뷰 UI, 에셋 적용

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#75]
## 💡 Issue
리포트뷰에 에셋, 컬러, 폰트를 추가합니다.

## 📝  todo
- [x] 리포트뷰 - 에셋 추가
- [x] 리포트뷰 - 컬러 적용
- [x] 리포트뷰 - 폰트 적용
- [x] 리포트 팝업 - 에셋, 컬러, 폰트 적용
- [x] 레이아웃 수정 부분 수정하기
