### ISSUE TITLE
[FEAT] 캐릭터 생성뷰 UI, 에셋적용

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#79]
## 💡 Issue
캐릭터 생성뷰에 색상, 폰트, 에셋 적용

## 📝  todo
- [x] 캐릭터 Flow1 색상, 폰트, 에셋 적용
- [x] 캐릭터 Flow2 색상, 폰트, 에셋 적용
- [x] 캐릭터 Flow3 색상, 폰트, 에셋 적용
