### ISSUE TITLE
[FEAT] Character뷰 전체 레이아웃 구성

### ISSUE THREAD

**Issue by heerucan** [TeamCatchMe/CatchMe-If-You-iOS#8]
## 💡 Issue
Character뷰 전체 Layout 구성

## 📝  todo
- [x] 상단 캐릭터 uiView 레이아웃 잡기
- [x] 캐릭터 리포트 headerView 레이아웃 잡기
- [x] 하단 contents cell 레이아웃 잡기
