### ISSUE TITLE
[FEAT] 캐츄수정 뷰 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#87]
## 💡 Issue
캐츄수정 뷰 레이아웃 구현 및 에셋 추가

## 📝  todo
- [x] 캐츄 수정 뷰 레이아웃 구현
- [x] 캐츄 수정 뷰 에셋 추가
- [x] 캐츄 수정 뷰 로직 구현
