### ISSUE TITLE
[CHORE] Character 뷰 및 팝업 레이아웃 변경

### ISSUE THREAD

**Issue by heerucan** [TeamCatchMe/CatchMe-If-You-iOS#90]
## 💡 Issue
디자인 변경에 따른 Character 뷰와 전반적인 팝업 레이아웃 변경

## 📝  todo
- [x] CharacterVC - 색상 변경
- [x] 캐츄 크기 변경
- [x] 캐칭! 워딩 변경
- [x] emptystate 위치 변경
- [x] Character 뷰 팝업 변경
- [x] AddAction 뷰 팝업 변경
