### ISSUE TITLE
[FEAT] 회원가입 뷰 서버 통신 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#98]
## 💡 Issue
회원가입 뷰에 있는 서버 통신을 구현합니다.

## 📝  todo
- [x] LoginService에 model, request 제대로 넣기
- [x] post하는 코드 짜기 -> LoginViewModel에
- [x] 코드 연결하기
- [x] 회원가입 다 하면 해당 아이디, 비밀번호 로그인으로 바로 반영되는 기능 구현
