### ISSUE TITLE
[FEAT] 이메일 중복체크 서버 통신 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-If-You-iOS#99]
## 💡 Issue
이메일을 중복체크하는 서버 통신을 구현합니다.

## 📝  todo
- [x] LoginService에 이메일 중복체크 코드 추가
- [x] LoginViewModel에 func 추가
- [x] 중복체크 되는지 확인하기
